const data = [
    {
        "id": 1,
        "status": 1,
        "createTime": "2018-05-17 01:02:54",
        "updateTime": "2018-05-17 01:02:54",
        "tails": {},
        "name": "用户中心",
        "type": "menu",
        "url": "",
        "permission": "",
        "parentId": 0,
        "icon": "2",
        "sort": 0,
        "subMenus": [
            {
                "id": 138,
                "status": 0,
                "createTime": "2020-03-11 01:28:55",
                "updateTime": "2020-03-11 01:28:55",
                "tails": {},
                "name": "用户管理",
                "type": "menu",
                "url": "/boss/user/index",
                "permission": "",
                "parentId": 1,
                "icon": null,
                "sort": 1,
                "subMenus": []
            },
            {
                "id": 159,
                "status": 0,
                "createTime": "2020-03-25 23:47:00",
                "updateTime": "2020-03-25 23:47:00",
                "tails": {},
                "name": "实名认证",
                "type": "menu",
                "url": "/boss/kyc/index",
                "permission": "",
                "parentId": 1,
                "icon": null,
                "sort": 2,
                "subMenus": []
            },
            {
                "id": 160,
                "status": 0,
                "createTime": "2020-03-26 01:40:02",
                "updateTime": "2020-03-26 01:40:02",
                "tails": {},
                "name": "视频认证",
                "type": "menu",
                "url": "/boss/videoAuth/index",
                "permission": "",
                "parentId": 1,
                "icon": null,
                "sort": 3,
                "subMenus": []
            },
            {
                "id": 161,
                "status": 0,
                "createTime": "2020-03-26 19:31:10",
                "updateTime": "2020-03-26 19:31:10",
                "tails": {},
                "name": "钱包地址",
                "type": "menu",
                "url": "/boss/assetAddress/index",
                "permission": "",
                "parentId": 1,
                "icon": null,
                "sort": 4,
                "subMenus": []
            },
            {
                "id": 162,
                "status": 0,
                "createTime": "2020-03-26 22:46:20",
                "updateTime": "2020-03-26 22:46:20",
                "tails": {},
                "name": "账户收付款",
                "type": "menu",
                "url": "/boss/assetMedium/index",
                "permission": "",
                "parentId": 1,
                "icon": null,
                "sort": 5,
                "subMenus": []
            },
            {
                "id": 171,
                "status": 0,
                "createTime": "2020-03-30 19:38:53",
                "updateTime": "2020-03-30 19:38:53",
                "tails": {},
                "name": "密码申诉管理",
                "type": "menu",
                "url": "/boss/editPwdAuditBill/index",
                "permission": "",
                "parentId": 1,
                "icon": null,
                "sort": 6,
                "subMenus": []
            }
        ]
    },
    {
        "id": 163,
        "status": 0,
        "createTime": "2020-03-28 00:02:55",
        "updateTime": "2020-03-28 00:02:55",
        "tails": {},
        "name": "广告商管理",
        "type": "menu",
        "url": "",
        "permission": "",
        "parentId": 0,
        "icon": null,
        "sort": 1,
        "subMenus": [
            {
                "id": 164,
                "status": 0,
                "createTime": "2020-03-28 00:03:47",
                "updateTime": "2020-03-28 00:03:47",
                "tails": {},
                "name": "广告商管理",
                "type": "menu",
                "url": "/boss/advertisers/index",
                "permission": "",
                "parentId": 163,
                "icon": null,
                "sort": 1,
                "subMenus": []
            },
            {
                "id": 180,
                "status": 0,
                "createTime": "2020-04-09 19:55:36",
                "updateTime": "2020-04-09 19:55:36",
                "tails": {},
                "name": "保证金账单",
                "type": "menu",
                "url": "/boss/advertisersBill/index",
                "permission": "",
                "parentId": 163,
                "icon": null,
                "sort": 2,
                "subMenus": []
            },
            {
                "id": 165,
                "status": 0,
                "createTime": "2020-03-28 04:58:54",
                "updateTime": "2020-03-28 04:58:54",
                "tails": {},
                "name": "保证金订单记录",
                "type": "menu",
                "url": "/boss/advertisersOrder/index",
                "permission": "",
                "parentId": 163,
                "icon": null,
                "sort": 2,
                "subMenus": []
            },
            {
                "id": 166,
                "status": 0,
                "createTime": "2020-03-28 18:14:42",
                "updateTime": "2020-03-28 18:14:42",
                "tails": {},
                "name": "OTC订单",
                "type": "menu",
                "url": "/boss/otcOrder/index",
                "permission": "",
                "parentId": 163,
                "icon": null,
                "sort": 3,
                "subMenus": []
            },
            {
                "id": 168,
                "status": 0,
                "createTime": "2020-03-29 00:11:47",
                "updateTime": "2020-03-29 00:11:47",
                "tails": {},
                "name": "配置项管理",
                "type": "menu",
                "url": "/boss/constantItem/index",
                "permission": "",
                "parentId": 163,
                "icon": null,
                "sort": 5,
                "subMenus": []
            },
            {
                "id": 155,
                "status": 0,
                "createTime": "2020-03-18 04:37:22",
                "updateTime": "2020-03-18 04:37:22",
                "tails": {},
                "name": "申请退保管理",
                "type": "menu",
                "url": "/boss/backMarginApprove/index",
                "permission": "",
                "parentId": 163,
                "icon": null,
                "sort": 6,
                "subMenus": []
            },
            {
                "id": 154,
                "status": 0,
                "createTime": "2020-03-17 19:03:32",
                "updateTime": "2020-03-17 19:03:32",
                "tails": {},
                "name": "申诉订单管理",
                "type": "menu",
                "url": "/boss/complainResult/index",
                "permission": "",
                "parentId": 163,
                "icon": null,
                "sort": 7,
                "subMenus": []
            },
            {
                "id": 181,
                "status": 0,
                "createTime": "2020-04-12 00:16:38",
                "updateTime": "2020-04-12 00:16:38",
                "tails": {},
                "name": "币种兑换UIGI汇率",
                "type": "menu",
                "url": "/boss/coinUigiRate/index",
                "permission": "",
                "parentId": 163,
                "icon": null,
                "sort": 9,
                "subMenus": []
            },
            {
                "id": 167,
                "status": 0,
                "createTime": "2020-03-28 22:23:49",
                "updateTime": "2020-03-28 22:23:49",
                "tails": {},
                "name": "法币兑换UIGI汇率",
                "type": "menu",
                "url": "/boss/uigiRate/index",
                "permission": "",
                "parentId": 163,
                "icon": null,
                "sort": 10,
                "subMenus": []
            },
            {
                "id": 186,
                "status": 0,
                "createTime": "2020-03-28 00:03:47",
                "updateTime": "2020-03-28 00:03:47",
                "tails": {},
                "name": "otc币种配置",
                "type": "menu",
                "url": "/boss/otcCoinSeting/index",
                "permission": "",
                "parentId": 163,
                "icon": null,
                "sort": 11,
                "subMenus": []
            }
        ]
    },
    {
        "id": 156,
        "status": 0,
        "createTime": "2020-03-18 22:36:52",
        "updateTime": "2020-03-18 22:36:52",
        "tails": {},
        "name": "社群中心",
        "type": "menu",
        "url": "",
        "permission": "",
        "parentId": 0,
        "icon": null,
        "sort": 2,
        "subMenus": [
            {
                "id": 169,
                "status": 0,
                "createTime": "2020-03-29 04:51:48",
                "updateTime": "2020-03-29 04:51:48",
                "tails": {},
                "name": "申请社群",
                "type": "menu",
                "url": "/boss/communityContract/index",
                "permission": "",
                "parentId": 156,
                "icon": null,
                "sort": 1,
                "subMenus": []
            },
            {
                "id": 157,
                "status": 0,
                "createTime": "2020-03-18 22:37:34",
                "updateTime": "2020-03-18 22:37:34",
                "tails": {},
                "name": "社群管理",
                "type": "menu",
                "url": "/boss/community/index",
                "permission": "",
                "parentId": 156,
                "icon": null,
                "sort": 2,
                "subMenus": []
            },
            {
                "id": 170,
                "status": 0,
                "createTime": "2020-03-29 04:52:28",
                "updateTime": "2020-03-29 04:52:28",
                "tails": {},
                "name": "社群更变记录",
                "type": "menu",
                "url": "/boss/communityContract/changeIndex",
                "permission": "",
                "parentId": 156,
                "icon": null,
                "sort": 3,
                "subMenus": []
            },
            {
                "id": 172,
                "status": 0,
                "createTime": "2020-03-31 18:48:39",
                "updateTime": "2020-03-31 18:48:39",
                "tails": {},
                "name": "社群记账权账户",
                "type": "menu",
                "url": "/boss/tallyReward/index",
                "permission": "",
                "parentId": 156,
                "icon": null,
                "sort": 4,
                "subMenus": []
            },
            {
                "id": 173,
                "status": 0,
                "createTime": "2020-03-31 22:26:28",
                "updateTime": "2020-03-31 22:26:28",
                "tails": {},
                "name": "社群记账权账户明细",
                "type": "menu",
                "url": "/boss/tallyRecord/index",
                "permission": "",
                "parentId": 156,
                "icon": null,
                "sort": 5,
                "subMenus": []
            },
            {
                "id": 174,
                "status": 0,
                "createTime": "2020-03-31 23:05:24",
                "updateTime": "2020-03-31 23:05:24",
                "tails": {},
                "name": "社群糖果账户",
                "type": "menu",
                "url": "/boss/goodcandyReward/index",
                "permission": "",
                "parentId": 156,
                "icon": null,
                "sort": 6,
                "subMenus": []
            },
            {
                "id": 175,
                "status": 0,
                "createTime": "2020-03-31 23:09:24",
                "updateTime": "2020-03-31 23:09:24",
                "tails": {},
                "name": "社群糖果账户明细",
                "type": "menu",
                "url": "/boss/goodcandyRecord/index",
                "permission": "",
                "parentId": 156,
                "icon": null,
                "sort": 7,
                "subMenus": []
            },
            {
                "id": 188,
                "status": 0,
                "createTime": "2020-06-25 00:36:00",
                "updateTime": "2020-06-25 00:36:00",
                "tails": {},
                "name": "更变社群记录",
                "type": "menu",
                "url": "/boss/userCommunityChangeRecord/index",
                "permission": "",
                "parentId": 156,
                "icon": null,
                "sort": 8,
                "subMenus": []
            },
            {
                "id": 202,
                "status": 0,
                "createTime": "2020-08-31 16:51:33",
                "updateTime": "2020-08-31 16:51:33",
                "tails": {},
                "name": "社群发展基金账户记录",
                "type": "menu",
                "url": "/boss/communityFundAccountRecord/index",
                "permission": "",
                "parentId": 156,
                "icon": null,
                "sort": 10,
                "subMenus": []
            },
            {
                "id": 203,
                "status": 0,
                "createTime": "2020-08-31 16:51:57",
                "updateTime": "2020-08-31 16:51:57",
                "tails": {},
                "name": "社群发展基金账户",
                "type": "menu",
                "url": "/boss/communityFundAccount/index",
                "permission": "",
                "parentId": 156,
                "icon": null,
                "sort": 11,
                "subMenus": []
            }
        ]
    },
    {
        "id": 158,
        "status": 0,
        "createTime": "2020-03-18 22:37:59",
        "updateTime": "2020-03-18 22:37:59",
        "tails": {},
        "name": "常用服务",
        "type": "menu",
        "url": "",
        "permission": "",
        "parentId": 0,
        "icon": null,
        "sort": 3,
        "subMenus": [
            {
                "id": 176,
                "status": 0,
                "createTime": "2020-04-01 00:09:05",
                "updateTime": "2020-04-01 00:09:05",
                "tails": {},
                "name": "用户糖果账户",
                "type": "menu",
                "url": "/boss/goodcandyReward/userIndex",
                "permission": "",
                "parentId": 158,
                "icon": null,
                "sort": 1,
                "subMenus": []
            },
            {
                "id": 177,
                "status": 0,
                "createTime": "2020-04-01 00:09:41",
                "updateTime": "2020-04-01 00:09:41",
                "tails": {},
                "name": "用户糖果账户明细",
                "type": "menu",
                "url": "/boss/goodcandyRecord/userIndex",
                "permission": "",
                "parentId": 158,
                "icon": null,
                "sort": 2,
                "subMenus": []
            },
            {
                "id": 178,
                "status": 0,
                "createTime": "2020-04-01 00:35:45",
                "updateTime": "2020-04-01 00:35:45",
                "tails": {},
                "name": "用户记账权账户",
                "type": "menu",
                "url": "/boss/tallyReward/userIndex",
                "permission": "",
                "parentId": 158,
                "icon": null,
                "sort": 3,
                "subMenus": []
            },
            {
                "id": 179,
                "status": 0,
                "createTime": "2020-04-01 00:37:07",
                "updateTime": "2020-04-01 00:37:07",
                "tails": {},
                "name": "用户记账权账户明细",
                "type": "menu",
                "url": "/boss/tallyRecord/userIndex",
                "permission": "",
                "parentId": 158,
                "icon": null,
                "sort": 4,
                "subMenus": []
            },
            {
                "id": 153,
                "status": 0,
                "createTime": "2020-03-17 03:31:06",
                "updateTime": "2020-03-17 03:31:06",
                "tails": {},
                "name": "记账上链审批",
                "type": "menu",
                "url": "/boss/tallyOrderBill/index",
                "permission": "",
                "parentId": 158,
                "icon": null,
                "sort": 5,
                "subMenus": []
            },
            {
                "id": 213,
                "status": 0,
                "createTime": "2020-09-16 11:01:38",
                "updateTime": "2020-09-16 11:01:38",
                "tails": {},
                "name": "合约订单记录",
                "type": "menu",
                "url": "/boss/contractOrderRecord/index",
                "permission": "",
                "parentId": 158,
                "icon": null,
                "sort": 7,
                "subMenus": []
            }
        ]
    },
    {
        "id": 135,
        "status": 0,
        "createTime": "2020-03-10 04:50:39",
        "updateTime": "2020-03-10 04:50:39",
        "tails": {},
        "name": "财务账户管理",
        "type": "menu",
        "url": "",
        "permission": "",
        "parentId": 0,
        "icon": null,
        "sort": 4,
        "subMenus": [
            {
                "id": 139,
                "status": 0,
                "createTime": "2020-03-11 17:12:20",
                "updateTime": "2020-03-11 17:12:20",
                "tails": {},
                "name": "账户管理",
                "type": "menu",
                "url": "/boss/assetAccount/index",
                "permission": "",
                "parentId": 135,
                "icon": null,
                "sort": 1,
                "subMenus": []
            },
            {
                "id": 182,
                "status": 0,
                "createTime": "2020-04-17 22:17:00",
                "updateTime": "2020-04-17 22:17:00",
                "tails": {},
                "name": "账单管理",
                "type": "menu",
                "url": "/boss/assetAccountRecord/index",
                "permission": "",
                "parentId": 135,
                "icon": null,
                "sort": 2,
                "subMenus": []
            },
            {
                "id": 187,
                "status": 0,
                "createTime": "2020-05-09 14:28:42",
                "updateTime": "2020-05-09 14:28:42",
                "tails": {},
                "name": "用户资金风控管理",
                "type": "menu",
                "url": "/boss/assetAccountBalanceApply/index",
                "permission": "",
                "parentId": 135,
                "icon": null,
                "sort": 3,
                "subMenus": []
            },
            {
                "id": 140,
                "status": 0,
                "createTime": "2020-03-11 17:13:28",
                "updateTime": "2020-03-11 17:13:28",
                "tails": {},
                "name": "充币记录",
                "type": "menu",
                "url": "/boss/chargeCoinApply/index",
                "permission": "",
                "parentId": 135,
                "icon": null,
                "sort": 4,
                "subMenus": []
            },
            {
                "id": 137,
                "status": 0,
                "createTime": "2020-03-10 22:02:57",
                "updateTime": "2020-03-10 22:02:57",
                "tails": {},
                "name": "提币管理",
                "type": "menu",
                "url": "/boss/carryCoin/index",
                "permission": "",
                "parentId": 135,
                "icon": null,
                "sort": 5,
                "subMenus": []
            },
            {
                "id": 141,
                "status": 0,
                "createTime": "2020-03-11 17:15:13",
                "updateTime": "2020-03-11 17:15:13",
                "tails": {},
                "name": "转账记录",
                "type": "menu",
                "url": "/boss/transfer/index",
                "permission": "",
                "parentId": 135,
                "icon": null,
                "sort": 6,
                "subMenus": []
            },
            {
                "id": 221,
                "status": 0,
                "createTime": "2020-10-17 11:20:31",
                "updateTime": "2020-10-17 11:20:31",
                "tails": {},
                "name": "冻结记录",
                "type": "menu",
                "url": "/boss/assetAccountFreezeRecord/index",
                "permission": "",
                "parentId": 135,
                "icon": null,
                "sort": 7,
                "subMenus": []
            }
        ]
    },
    {
        "id": 215,
        "status": 0,
        "createTime": "2020-10-15 14:37:58",
        "updateTime": "2020-10-15 14:37:58",
        "tails": {},
        "name": "平台数据概况",
        "type": "menu",
        "url": "",
        "permission": "",
        "parentId": 0,
        "icon": null,
        "sort": 5,
        "subMenus": [
            {
                "id": 216,
                "status": 0,
                "createTime": "2020-10-15 14:38:27",
                "updateTime": "2020-10-15 14:38:27",
                "tails": {},
                "name": "GoodCoin数据概况",
                "type": "menu",
                "url": "/boss/statsGoodCoinDataView/index",
                "permission": "",
                "parentId": 215,
                "icon": null,
                "sort": 1,
                "subMenus": []
            },
            {
                "id": 217,
                "status": 0,
                "createTime": "2020-10-15 14:38:45",
                "updateTime": "2020-10-15 14:38:45",
                "tails": {},
                "name": "GoodCoin每⽇数据",
                "type": "menu",
                "url": "/boss/statsGoodCoinDaily/index",
                "permission": "",
                "parentId": 215,
                "icon": null,
                "sort": 2,
                "subMenus": []
            },
            {
                "id": 218,
                "status": 0,
                "createTime": "2020-10-15 14:38:58",
                "updateTime": "2020-10-15 14:38:58",
                "tails": {},
                "name": "GlobalCoin数据概况",
                "type": "menu",
                "url": "/boss/statsGlobalCoinDataView/index",
                "permission": "",
                "parentId": 215,
                "icon": null,
                "sort": 3,
                "subMenus": []
            },
            {
                "id": 219,
                "status": 0,
                "createTime": "2020-10-15 14:39:14",
                "updateTime": "2020-10-15 14:39:14",
                "tails": {},
                "name": "GlobalCoin每⽇数据",
                "type": "menu",
                "url": "/boss/statsGlobalCoinDaily/index",
                "permission": "",
                "parentId": 215,
                "icon": null,
                "sort": 4,
                "subMenus": []
            },
            {
                "id": 220,
                "status": 0,
                "createTime": "2020-10-16 10:13:27",
                "updateTime": "2020-10-16 10:13:27",
                "tails": {},
                "name": "每日数据推送记录",
                "type": "menu",
                "url": "/boss/statsDailyPushRecord/index",
                "permission": "",
                "parentId": 215,
                "icon": null,
                "sort": 5,
                "subMenus": []
            }
        ]
    },
    {
        "id": 145,
        "status": 0,
        "createTime": "2020-03-12 03:07:37",
        "updateTime": "2020-03-12 03:07:37",
        "tails": {},
        "name": "开放中心",
        "type": "menu",
        "url": "",
        "permission": "",
        "parentId": 0,
        "icon": null,
        "sort": 5,
        "subMenus": [
            {
                "id": 142,
                "status": 0,
                "createTime": "2020-03-11 17:16:32",
                "updateTime": "2020-03-11 17:16:32",
                "tails": {},
                "name": "商户应用",
                "type": "menu",
                "url": "/boss/mchApplication/index",
                "permission": "",
                "parentId": 145,
                "icon": null,
                "sort": 1,
                "subMenus": []
            },
            {
                "id": 143,
                "status": 0,
                "createTime": "2020-03-11 17:18:26",
                "updateTime": "2020-03-11 17:18:26",
                "tails": {},
                "name": "开放应用",
                "type": "menu",
                "url": "/boss/openApplication/index",
                "permission": "",
                "parentId": 145,
                "icon": null,
                "sort": 2,
                "subMenus": []
            },
            {
                "id": 144,
                "status": 0,
                "createTime": "2020-03-11 17:18:54",
                "updateTime": "2020-03-11 17:18:54",
                "tails": {},
                "name": "开放应用功能",
                "type": "menu",
                "url": "/boss/openApplicationInterface/index",
                "permission": "",
                "parentId": 145,
                "icon": null,
                "sort": 3,
                "subMenus": []
            }
        ]
    },
    {
        "id": 151,
        "status": 0,
        "createTime": "2020-03-15 03:52:48",
        "updateTime": "2020-03-15 03:52:48",
        "tails": {},
        "name": "币种管理",
        "type": "menu",
        "url": "",
        "permission": "",
        "parentId": 0,
        "icon": null,
        "sort": 6,
        "subMenus": [
            {
                "id": 152,
                "status": 0,
                "createTime": "2020-03-15 04:48:06",
                "updateTime": "2020-03-15 04:48:06",
                "tails": {},
                "name": "币种管理",
                "type": "menu",
                "url": "/boss/coinSetting/index",
                "permission": "",
                "parentId": 151,
                "icon": null,
                "sort": 1,
                "subMenus": []
            }
        ]
    },
    {
        "id": 147,
        "status": 0,
        "createTime": "2020-03-14 19:40:01",
        "updateTime": "2020-03-14 19:40:01",
        "tails": {},
        "name": "运营管理",
        "type": "menu",
        "url": "",
        "permission": "",
        "parentId": 0,
        "icon": null,
        "sort": 7,
        "subMenus": [
            {
                "id": 148,
                "status": 0,
                "createTime": "2020-03-14 19:42:31",
                "updateTime": "2020-03-14 19:42:31",
                "tails": {},
                "name": "文案分享",
                "type": "menu",
                "url": "/boss/ins/index",
                "permission": "",
                "parentId": 147,
                "icon": null,
                "sort": 1,
                "subMenus": []
            },
            {
                "id": 149,
                "status": 0,
                "createTime": "2020-03-14 19:44:01",
                "updateTime": "2020-03-14 19:44:01",
                "tails": {},
                "name": "海报分享",
                "type": "menu",
                "url": "/boss/poster/index",
                "permission": "",
                "parentId": 147,
                "icon": null,
                "sort": 2,
                "subMenus": []
            },
            {
                "id": 150,
                "status": 0,
                "createTime": "2020-03-14 19:44:42",
                "updateTime": "2020-03-14 19:44:42",
                "tails": {},
                "name": "邀请排行榜",
                "type": "menu",
                "url": "/boss/inviteTop/index",
                "permission": "",
                "parentId": 147,
                "icon": null,
                "sort": 3,
                "subMenus": []
            },
            {
                "id": 214,
                "status": 0,
                "createTime": "2020-09-17 16:36:13",
                "updateTime": "2020-09-17 16:36:13",
                "tails": {},
                "name": "APP版本管理",
                "type": "menu",
                "url": "/boss/appVersion/index",
                "permission": "",
                "parentId": 147,
                "icon": null,
                "sort": 6,
                "subMenus": []
            },
            {
                "id": 189,
                "status": 0,
                "createTime": "2020-06-27 10:48:40",
                "updateTime": "2020-06-27 10:48:40",
                "tails": {},
                "name": "系统通知",
                "type": "menu",
                "url": "/boss/article/index",
                "permission": "",
                "parentId": 147,
                "icon": null,
                "sort": 10,
                "subMenus": []
            },
            {
                "id": 184,
                "status": 0,
                "createTime": "2020-05-09 09:42:46",
                "updateTime": "2020-05-09 09:42:46",
                "tails": {},
                "name": "问答中心",
                "type": "menu",
                "url": "/boss/question/index",
                "permission": "",
                "parentId": 147,
                "icon": null,
                "sort": 12,
                "subMenus": []
            }
        ]
    },
    {
        "id": 8,
        "status": 1,
        "createTime": "2017-12-21 00:40:06",
        "updateTime": "2017-12-21 00:40:06",
        "tails": {},
        "name": "系统管理",
        "type": "menu",
        "url": "",
        "permission": "",
        "parentId": 0,
        "icon": "1",
        "sort": 8,
        "subMenus": [
            {
                "id": 9,
                "status": 1,
                "createTime": "2017-12-22 23:31:05",
                "updateTime": "2017-12-22 23:31:05",
                "tails": {},
                "name": "资源管理",
                "type": "menu",
                "url": "/boss/sysResources/index",
                "permission": "sysResources",
                "parentId": 8,
                "icon": "1",
                "sort": 1,
                "subMenus": []
            },
            {
                "id": 14,
                "status": 1,
                "createTime": "2017-12-22 23:31:27",
                "updateTime": "2017-12-22 23:31:27",
                "tails": {},
                "name": "角色管理",
                "type": "menu",
                "url": "/boss/sysRole/index",
                "permission": "sysRoles",
                "parentId": 8,
                "icon": "2",
                "sort": 2,
                "subMenus": []
            },
            {
                "id": 2,
                "status": 1,
                "createTime": "2017-12-22 21:56:15",
                "updateTime": "2017-12-22 21:56:15",
                "tails": {},
                "name": "账号列表",
                "type": "menu",
                "url": "/boss/sysUser/index",
                "permission": "users",
                "parentId": 8,
                "icon": "1",
                "sort": 3,
                "subMenus": []
            },
            {
                "id": 146,
                "status": 0,
                "createTime": "2020-03-13 22:41:38",
                "updateTime": "2020-03-13 22:41:38",
                "tails": {},
                "name": "字典管理",
                "type": "menu",
                "url": "/boss/sysDict/index",
                "permission": "",
                "parentId": 8,
                "icon": null,
                "sort": 4,
                "subMenus": []
            },
            {
                "id": 183,
                "status": 0,
                "createTime": "2020-04-25 17:55:44",
                "updateTime": "2020-04-25 17:55:44",
                "tails": {},
                "name": "系统操作日志",
                "type": "menu",
                "url": "/boss/sysLog/index",
                "permission": "",
                "parentId": 8,
                "icon": null,
                "sort": 10,
                "subMenus": []
            }
        ]
    },
    {
        "id": 190,
        "status": 0,
        "createTime": "2020-08-27 21:51:51",
        "updateTime": "2020-08-27 21:51:51",
        "tails": {},
        "name": "消费记账",
        "type": "menu",
        "url": "",
        "permission": "",
        "parentId": 0,
        "icon": null,
        "sort": 11,
        "subMenus": [
            {
                "id": 211,
                "status": 0,
                "createTime": "2020-09-11 19:45:28",
                "updateTime": "2020-09-11 19:45:28",
                "tails": {},
                "name": "消费记账系统配置",
                "type": "menu",
                "url": "/boss/bookkeepingSetting/index",
                "permission": "",
                "parentId": 190,
                "icon": null,
                "sort": 1,
                "subMenus": []
            },
            {
                "id": 193,
                "status": 0,
                "createTime": "2020-08-27 21:55:20",
                "updateTime": "2020-08-27 21:55:20",
                "tails": {},
                "name": "商家管理",
                "type": "menu",
                "url": "/boss/bkMerchant/index",
                "permission": "",
                "parentId": 190,
                "icon": null,
                "sort": 1,
                "subMenus": []
            },
            {
                "id": 192,
                "status": 0,
                "createTime": "2020-08-27 21:54:35",
                "updateTime": "2020-08-27 21:54:35",
                "tails": {},
                "name": "商家优惠信息",
                "type": "menu",
                "url": "/boss/mchDiscountInfo/index",
                "permission": "",
                "parentId": 190,
                "icon": null,
                "sort": 2,
                "subMenus": []
            },
            {
                "id": 191,
                "status": 0,
                "createTime": "2020-08-27 21:53:44",
                "updateTime": "2020-08-27 21:53:44",
                "tails": {},
                "name": "商家优惠方案",
                "type": "menu",
                "url": "/boss/mchDiscountSetting/index",
                "permission": "",
                "parentId": 190,
                "icon": null,
                "sort": 3,
                "subMenus": []
            },
            {
                "id": 194,
                "status": 0,
                "createTime": "2020-08-27 21:56:46",
                "updateTime": "2020-08-27 21:56:46",
                "tails": {},
                "name": "消费记账记录",
                "type": "menu",
                "url": "/boss/bkBookkeeping/index",
                "permission": "",
                "parentId": 190,
                "icon": null,
                "sort": 4,
                "subMenus": []
            },
            {
                "id": 195,
                "status": 0,
                "createTime": "2020-08-27 21:57:30",
                "updateTime": "2020-08-27 21:57:30",
                "tails": {},
                "name": "记账权账户",
                "type": "menu",
                "url": "/boss/beAccount/index",
                "permission": "",
                "parentId": 190,
                "icon": null,
                "sort": 5,
                "subMenus": []
            },
            {
                "id": 196,
                "status": 0,
                "createTime": "2020-08-27 21:58:10",
                "updateTime": "2020-08-27 21:58:10",
                "tails": {},
                "name": "记账权账户明细 ",
                "type": "menu",
                "url": "/boss/beAccountRecord/index",
                "permission": "",
                "parentId": 190,
                "icon": null,
                "sort": 6,
                "subMenus": []
            },
            {
                "id": 197,
                "status": 0,
                "createTime": "2020-08-27 21:58:46",
                "updateTime": "2020-08-27 21:58:46",
                "tails": {},
                "name": "权益上链记录",
                "type": "menu",
                "url": "/boss/beChain/index",
                "permission": "",
                "parentId": 190,
                "icon": null,
                "sort": 7,
                "subMenus": []
            },
            {
                "id": 198,
                "status": 0,
                "createTime": "2020-08-27 21:59:24",
                "updateTime": "2020-08-27 21:59:24",
                "tails": {},
                "name": "授权帐号",
                "type": "menu",
                "url": "/boss/authorizedAssetAccount/index",
                "permission": "",
                "parentId": 190,
                "icon": null,
                "sort": 8,
                "subMenus": []
            },
            {
                "id": 199,
                "status": 0,
                "createTime": "2020-08-27 21:59:48",
                "updateTime": "2020-08-27 21:59:48",
                "tails": {},
                "name": "授权帐号资金明细",
                "type": "menu",
                "url": "/boss/authAccountRecord/index",
                "permission": "",
                "parentId": 190,
                "icon": null,
                "sort": 9,
                "subMenus": []
            },
            {
                "id": 200,
                "status": 0,
                "createTime": "2020-08-27 22:00:24",
                "updateTime": "2020-08-27 22:00:24",
                "tails": {},
                "name": "授权资金申请记录",
                "type": "menu",
                "url": "/boss/authorizedBalanceRecord/index",
                "permission": "",
                "parentId": 190,
                "icon": null,
                "sort": 10,
                "subMenus": []
            },
            {
                "id": 201,
                "status": 0,
                "createTime": "2020-08-27 22:00:48",
                "updateTime": "2020-08-27 22:00:48",
                "tails": {},
                "name": "消费类型",
                "type": "menu",
                "url": "/boss/bkTradeType/index",
                "permission": "",
                "parentId": 190,
                "icon": null,
                "sort": 11,
                "subMenus": []
            },
            {
                "id": 204,
                "status": 0,
                "createTime": "2020-09-05 16:24:06",
                "updateTime": "2020-09-05 16:24:06",
                "tails": {},
                "name": "商家商品管理",
                "type": "menu",
                "url": "/boss/bkMerchantProduct/index",
                "permission": "",
                "parentId": 190,
                "icon": null,
                "sort": 12,
                "subMenus": []
            },
            {
                "id": 205,
                "status": 0,
                "createTime": "2020-09-08 10:34:20",
                "updateTime": "2020-09-08 10:34:20",
                "tails": {},
                "name": "收藏商家",
                "type": "menu",
                "url": "/boss/bkMerchantCollect/index",
                "permission": "",
                "parentId": 190,
                "icon": null,
                "sort": 14,
                "subMenus": []
            },
            {
                "id": 206,
                "status": 0,
                "createTime": "2020-09-08 11:38:07",
                "updateTime": "2020-09-08 11:38:07",
                "tails": {},
                "name": "商家糖果额度账户",
                "type": "menu",
                "url": "/boss/bkCandyQuotaAccount/index",
                "permission": "",
                "parentId": 190,
                "icon": null,
                "sort": 15,
                "subMenus": []
            },
            {
                "id": 207,
                "status": 0,
                "createTime": "2020-09-08 14:56:00",
                "updateTime": "2020-09-08 14:56:00",
                "tails": {},
                "name": "商家糖果额度账单",
                "type": "menu",
                "url": "/boss/bkCandyQuotaAccountRecord/index",
                "permission": "",
                "parentId": 190,
                "icon": null,
                "sort": 16,
                "subMenus": []
            },
            {
                "id": 208,
                "status": 0,
                "createTime": "2020-09-08 15:11:51",
                "updateTime": "2020-09-08 15:11:51",
                "tails": {},
                "name": "商家营业时间",
                "type": "menu",
                "url": "/boss/bkMerchantHours/index",
                "permission": "",
                "parentId": 190,
                "icon": null,
                "sort": 17,
                "subMenus": []
            },
            {
                "id": 209,
                "status": 0,
                "createTime": "2020-09-09 15:11:35",
                "updateTime": "2020-09-09 15:11:35",
                "tails": {},
                "name": "商家糖果额度申请",
                "type": "menu",
                "url": "/boss/bkCandyQuotaApply/index",
                "permission": "",
                "parentId": 190,
                "icon": null,
                "sort": 18,
                "subMenus": []
            },
            {
                "id": 210,
                "status": 0,
                "createTime": "2020-09-10 11:16:43",
                "updateTime": "2020-09-10 11:16:43",
                "tails": {},
                "name": "商家审核",
                "type": "menu",
                "url": "/boss/bkMerchantVerifyRecord/index",
                "permission": "",
                "parentId": 190,
                "icon": null,
                "sort": 19,
                "subMenus": []
            },
            {
                "id": 212,
                "status": 0,
                "createTime": "2020-09-12 10:45:39",
                "updateTime": "2020-09-12 10:45:39",
                "tails": {},
                "name": "消费评价",
                "type": "menu",
                "url": "/boss/bkBookkeepingEvaluate/index",
                "permission": "",
                "parentId": 190,
                "icon": null,
                "sort": 20,
                "subMenus": []
            }
        ]
    },
    {
        "id": 223,
        "status": 0,
        "createTime": "2020-10-21 16:04:03",
        "updateTime": "2020-10-21 16:04:03",
        "tails": {},
        "name": "交易所",
        "type": "menu",
        "url": "",
        "permission": "",
        "parentId": 0,
        "icon": null,
        "sort": 18,
        "subMenus": [
            {
                "id": 226,
                "status": 0,
                "createTime": "2020-10-21 16:06:49",
                "updateTime": "2020-10-21 16:06:49",
                "tails": {},
                "name": "账户信息",
                "type": "menu",
                "url": "/boss/bbexchange/account/index",
                "permission": "",
                "parentId": 223,
                "icon": null,
                "sort": 1,
                "subMenus": []
            },
            {
                "id": 225,
                "status": 0,
                "createTime": "2020-10-21 16:06:12",
                "updateTime": "2020-10-21 16:06:12",
                "tails": {},
                "name": "产品交易对",
                "type": "menu",
                "url": "/boss/bbexchange/product/index",
                "permission": "",
                "parentId": 223,
                "icon": null,
                "sort": 2,
                "subMenus": []
            },
            {
                "id": 227,
                "status": 0,
                "createTime": "2020-10-21 16:07:37",
                "updateTime": "2020-10-21 16:07:37",
                "tails": {},
                "name": "账单信息",
                "type": "menu",
                "url": "/boss/bbexchange/bill/index",
                "permission": "",
                "parentId": 223,
                "icon": null,
                "sort": 3,
                "subMenus": []
            },
            {
                "id": 224,
                "status": 0,
                "createTime": "2020-10-21 16:05:29",
                "updateTime": "2020-10-21 16:05:29",
                "tails": {},
                "name": "订单信息",
                "type": "menu",
                "url": "/boss/bbexchange/order/index",
                "permission": "",
                "parentId": 223,
                "icon": null,
                "sort": 4,
                "subMenus": []
            },
            {
                "id": 228,
                "status": 0,
                "createTime": "2020-10-22 09:16:12",
                "updateTime": "2020-10-22 09:16:12",
                "tails": {},
                "name": "账单信息",
                "type": "menu",
                "url": "/boss/bbexchange/bill/index",
                "permission": "",
                "parentId": 223,
                "icon": null,
                "sort": 5,
                "subMenus": []
            }
        ]
    }
]
